[package]
name = "stabilizer"
version = "0.1.0"
edition = "2021"

[dependencies]
rtic-time = { optional = true, git = "https://github.com/Sympatron/rtic.git" }

[features]
default = ["rtic-time"]

[dev-dependencies]
fugit = "0.3.7"
